version: 2
jobs:
  build_deploy:
    docker:
      - image: node:10.11-alpine
    steps:
      - checkout
      - run:
          name: Install npm packages
          command: yarn install --frozen-packages
      - run:
          name: Build static files
          command: yarn build
      - run:
          name: Deploy
          command: |
            apk --no-cache add git
            git config user.email "ci-build@jonathanstriebel.de"
            git config user.name "ci-build"
            yarn deploy

workflows:
  version: 2
  default:
    jobs:
      - build_deploy
